# Board clock and forwarded LTC2208 encode clock.
create_clock -name sys_clk -period 20.000 [get_ports sys_clk]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

# The encode clock is generated by an ODDR from the 0-degree 50 MHz clock.
create_generated_clock -name adc_b_encode_clk \
    -source [get_ports sys_clk] -divide_by 1 [get_ports adc_b_clk]

# Channel B initially inherits the existing 135-degree capture phase.  The
# channel-A board result is not a final channel-B timing conclusion: scan the
# channel-B stable phase window on hardware before release.  Numeric
# set_input_delay constraints are deliberately withheld until the outbound
# clock and inbound data PCB delays are known; do not substitute CLKOUT skew.
