`ifndef MEASUREMENT_DEFS_SVH
`define MEASUREMENT_DEFS_SVH

`define MEAS_FORMAT_VERSION       32'h0001_0001
`define MEAS_TIME_MAGIC           32'h5449_4D45
`define MEAS_SPECTRUM_MAGIC       32'h5350_4543
`define MEAS_TRAILER_WORDS        16
`define MEAS_SPECTRUM_TRAILER_BEATS 8
`define MEAS_SHORT_SAMPLES        65536
`define MEAS_POSITIVE_BINS        32769

`define MEAS_CTRL_RUN             0
`define MEAS_CTRL_SOFT_RESET      1
`define MEAS_CTRL_FFT_ENABLE      2

`define MEAS_STATUS_MMCM_LOCKED   0
`define MEAS_STATUS_FRAME_ACTIVE  1
`define MEAS_STATUS_INPUT_STALL   2
`define MEAS_STATUS_FFT_ACTIVE    3
`define MEAS_STATUS_SPECTRUM_BUSY 4
`define MEAS_STATUS_FFT_EVENT_LSB 9
`define MEAS_STATUS_EPOCH_LSB     16

`endif
